Fixed "setuidgid: usage: setuidgid account child"
Convert .release to Procfile and use foreman to start process

diff --git a/builder/builder b/builder/builder
--- a/builder/builder
+++ b/builder/builder
@@ -67,16 +67,18 @@ hash -r
 
 case "\$(basename \$0)" in
   start)
-    if [[ -f Procfile ]]; then
-      command="foreman start --procfile=Procfile \$@"
-    else
-      command="\$(ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['\$1']")"
-    fi
+    [[ ! -f Procfile ]] && ruby -e "require 'yaml';File.write('Procfile', (YAML.load_file('.release')['default_process_types'] || {}).to_yaml)" 
+    command="foreman start --procfile=Procfile \$@"
     ;;
   *)
     command="\$@"
     ;;
 esac
+
+if [[ -z "\$command" ]]; then
+  echo "Missing command (\$@)"
+  exit 1
+fi
 
 exec setuidgid $user_name \$(eval echo \${command})
 EOF
